In [1]:
[[123, 12, 25, 16, 98],[],[]]

[[123, 12, 25, 16, 98], [], []]

In [7]:
import numpy
n=numpy.arange(27)


In [5]:
type(n)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [8]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
import numpy as np
m=np.asarray([[123, 12, 25, 16, 98],[],[]], dtype=object)
print(m)

[list([123, 12, 25, 16, 98]) list([]) list([])]


In [2]:
import cv2

In [3]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [5]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)